FROM neo4j:5

# Expose Neo4j HTTP and Bolt ports
EXPOSE 7474 7687

# Set default environment variables (Neo4j username/password)
ENV NEO4J_AUTH=neo4j/testpassword
ENV NEO4J_dbms_default__listen__address=0.0.0.0

