version: '3.8'

services:
  db:
    build:
      context: ./postgres
    container_name: divhacks_postgres_db
    restart: always
    environment:
      POSTGRES_USER: divhack_user
      POSTGRES_PASSWORD: divhacks2025
      POSTGRES_DB: divhacks_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - divhacks_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U divhack_user -d divhacks_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  nessie_ingest:
    build:
      context: ./fastapi
    container_name: divhacks_nessie_ingest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - divhacks_network
    command: >
      sh -c "echo '⏳ Waiting for DB...' && sleep 5 &&
             python3 -m fastapi.app.database.nessie_ingest"
    restart: "no"   # Only runs once and exits

  neo4j:
    build:
      context: ./neo4j
    container_name: divhacks_neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/divhacks2025
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - divhacks_network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p divhacks2025 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: ./fastapi
    container_name: divhacks_fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - divhacks_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: divhacks_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./env.env
    environment:
      NODE_ENV: production
    depends_on:
      - fastapi
    networks:
      - divhacks_network
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  db_data:
  neo4j_data:
  neo4j_logs:

networks:
  divhacks_network:
    driver: bridge